### ISSUE TITLE
Game Pauses frequently 

### ISSUE THREAD

**Issue by Prakash19921206** [BayatGames/RedRunner#3]
i downloaded the game from [here ](https://bayat.itch.io/red-runner/download/eyJleHBpcmVzIjoxNTI2MjIwOTgxLCJpZCI6MTU4NTg4fQ%3d%3d.wOq8zMa%2frAHryblYfVU%2ffeyk%2bEc%3d)
It works fine, except it pauses automatically... 
i just keep moving forward, then when i press space(jump), it shows the pause menu...

some bug in the code, that bring pause menu when multiple keys are pressed.

i'm running on windows 7 64bit
[unity not installed, just tried the executable directly]

**Update :** This happens only when i run in full screen mode, however in windowed mode(any resolution, quality) there is no issue

**Comment by hasanbayatme** [comment]
Hi.
It is a known issue, it is caused because the Pause button is focused button, so it got activated by Space button.
So, for jump press up arrow or W.

**Comment by Prakash19921206** [comment]
Thanks for your reply.  using up arrow worked!
but is there a way to solve Space bar button issue?

**Comment by hasanbayatme** [comment]
To make the Space button working, we need to leave pause button unfocused when Game starts, or we can change the UI interaction button to Enter instead of Space.
Thanks.

**Comment by Prakash19921206** [comment]
Ok.. Thanks

**Comment by escape0707** [comment]
Changing `Canvas` - `In-Game Screen` - `Pause Button`'s `Inspector` - `UI Button` - `Navigation` option to `None` solves this problem, by disallowing Unity to change focus onto it.
