### ISSUE TITLE
Problem with UI screens transition

### ISSUE THREAD

**Issue by AyoubGharbi** [BayatGames/RedRunner#4]
- When the pause screen is displayed and you press Escape again : 
   * Normal Behavior: 
      The pause screen is deactivated.
   * Current Behavior:
      The UI Manager keep calling the function to open the pause screen again.
=> From players perspective, the Escape key need to switch between activating and deactivating the pause screen, also the additional call to the function can cause problems especially if there is callbacks affectations in there.

**Comment by hasanbayatme** [comment]
Yes, that's a known issue, thanks for reporting!
